name: MyWarp
author: ImOlli
version: 1.2.1
main: de.ImOlli.mywarp.MyWarp

commands:
  warp:
    description: Warps you to an warppoint.
  setwarp:
    description: Creates an warppoint.
  delwarp:
    description: Removes an warpoint.
  warps:
    description: Show you all warppoints.
  mywarp:
    description: Maincommand.
  warpgui:
    description: Opens an WarpGUI.