name: MyWarp
author: ImOlli
version: 1.7
description: This Plugin give you the ability to create warppoints.
main: de.imolli.mywarp.MyWarp

softdepend: [Vault]

commands:
  warp:
    description: Warps you to an warppoint.
    usage: /warp [Name]
    permission: MyWarp.warp.warp
  setwarp:
    description: Creates an new warppoint.
    usage: /setwarp [Name]
    permission: MyWarp.warp.create
  delwarp:
    description: Removes an warppoint.
    usage: /delwarp [Name]
    permission: MyWarp.warp.delete
  warps:
    description: Show you all available warppoints.
    usage: /warps
    permission: MyWarp.warps
  mywarp:
    description: Maincommand.
    usage: /mywarp <reload>
    permission: MyWarp.mywarp
  warpgui:
    description: Opens an Teleport WarpGUI.
    usage: /warpgui
    permission: MyWarp.warp.warp
  warpcoins:
    description: Shows you your amount of Warpcoins.
    usage: /warpcoins <add|get|remove> <player> <amount>
    permission: MyWarp.warpcoins.basic

permissions:
  MyWarp.*:
    description: Gives you all permissions.
    children:
      MyWarp.warp.warp: true
      MyWarp.warp.create: true
      MyWarp.warp.delete: true
      MyWarp.warps: true
      MyWarp.mywarp: true
      MyWarp.warpcoins.basic: true
      MyWarp.warpcoins.add: true
      MyWarp.warpcoins.get: true
      MyWarp.warpcoins.remove: true
      MyWarp.warpcosts.ignore: true
    default: not op
  MyWarp.warpcoins.*:
    description: Gives you all permission for the command warpcoins.
    default: op
    children:
      MyWarp.warpcoins.basic: true
      MyWarp.warpcoins.add: true
      MyWarp.warpcoins.get: true
      MyWarp.warpcoins.remove: true
  MyWarp.warp.warp:
    description: Gives you the permission to warp to warppoints.
    default: true
  MyWarp.warp.create:
    description: Gives you the permission to create warppoints.
    default: op
  MyWarp.warp.delete:
    description: Gives you the permission to delete warppoints.
    default: op
  MyWarp.warps:
    description: Gives you the permission to show all list of all warppoints.
    default: true
  MyWarp.mywarp:
    description: Gives you the permission to reload MyWarp.
    default: op
  MyWarp.warpcoins.basic:
    description: Gives you the permission to show you your amount of coins.
    default: true
  MyWarp.warpcoins.add:
    description: Gives you the permission to add a player an amount of coins.
    default: op
  MyWarp.warpcoins.get:
    description: Gives you the permission to show you the amount of coins of a player.
    default: op
  MyWarp.warpcoins.remove:
    description: Gives you the permission to remove a palyer an amount of coins.
    default: op
  MyWarp.warpcosts.ignore:
    description: Gives you the abillity to ignore all warpcosts.
    default: not op